/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjahit.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ukuran extends javax.swing.JFrame {

    /**
     * Creates new form ukuran
     */
    DefaultTableModel model;
    public ukuran() {
        initComponents();
        //menampilkan judul dari tabel
        String [] judul= {"Nama Konsumen","PBaju","LB","LD","LP","LPinggulAtas","PL",
        "LPergelanganTangan","LLeher","PCelana","LPinggang","LPinggul","LPaha","Selangkangan","LLutut","LPergelanganKaki"};
        model = new DefaultTableModel(judul,0);
        tabelukuran.setModel(model);
        tampilkan();
            
        
    }

    private void tampilkan() {//method tampil
      int row =tabelukuran.getRowCount();
        for(int a= 0; a<row;a++){
            model.removeRow(0);
        }
        try{
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/penjahit","root","");
        ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM ukuran");
        while(rs.next()){
            String data []= {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),
            rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13),rs.getString(14),rs.getString(15),
            rs.getString(16)};
            model.addRow(data);
        } 
    } catch (SQLException ex){
        java.util.logging.Logger.getLogger(DataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tpBaju = new javax.swing.JTextField();
        tLebarBahu = new javax.swing.JTextField();
        tLD = new javax.swing.JTextField();
        tLPerut = new javax.swing.JTextField();
        tLPinggulAtas = new javax.swing.JTextField();
        tLLeher = new javax.swing.JTextField();
        tPCelana = new javax.swing.JTextField();
        tLPinggang = new javax.swing.JTextField();
        tLPinggul = new javax.swing.JTextField();
        tLPaha = new javax.swing.JTextField();
        tSelang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tPL = new javax.swing.JTextField();
        tLLutut = new javax.swing.JTextField();
        tLPergelanganKaki = new javax.swing.JTextField();
        tLPergelanganTangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelukuran = new javax.swing.JTable();
        simpanbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        tambahBtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 216, 174));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 50)); // NOI18N
        jLabel1.setText("UKURAN");

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Keluar");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(425, 425, 425)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel2.setText("Nama Konsumen");

        jLabel3.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel3.setText("Panjang Baju");

        jLabel4.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel4.setText("Lebar Bahu");

        jLabel5.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel5.setText("Lingkar Dada");

        jLabel6.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel6.setText("Lingkar Perut");

        jLabel7.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel7.setText("Lingkar Pinggul Atas");

        jLabel8.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel8.setText("Lingkar Leher");

        jLabel9.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel9.setText("Panjang Celana");

        jLabel10.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel10.setText("Lingkar Pinggang");

        jLabel11.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel11.setText("Lingkar Pinggul");

        jLabel12.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel12.setText("Lingkar Paha");

        jLabel13.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel13.setText("Selangkangan");

        jLabel14.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel14.setText("Panjang Lengan");

        jLabel15.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel15.setText("Lingkar Lutut");

        jLabel16.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel16.setText("Lingkar Pergelangan Tangan");

        jLabel17.setFont(new java.awt.Font("Hobo Std", 0, 14)); // NOI18N
        jLabel17.setText("Lingkar Pergelangan Kaki");

        tabelukuran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelukuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelukuranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelukuran);

        simpanbtn.setBackground(new java.awt.Color(255, 204, 153));
        simpanbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simpanbtn.setText("Simpan");
        simpanbtn.setBorder(null);
        simpanbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanbtnMouseClicked(evt);
            }
        });

        editbtn.setBackground(new java.awt.Color(255, 204, 153));
        editbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editbtn.setText("Edit");
        editbtn.setBorder(null);
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        hapusbtn.setBackground(new java.awt.Color(255, 204, 153));
        hapusbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hapusbtn.setText("Hapus");
        hapusbtn.setBorder(null);
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        tambahBtn.setBackground(new java.awt.Color(255, 204, 153));
        tambahBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambahBtn.setText("Tambah");
        tambahBtn.setBorder(null);
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        resetbtn.setBackground(new java.awt.Color(255, 204, 153));
        resetbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.setBorder(null);
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(simpanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tLD, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(tLPerut)
                            .addComponent(tLPinggulAtas)
                            .addComponent(tPL)
                            .addComponent(tLPergelanganTangan)
                            .addComponent(tpBaju)
                            .addComponent(tLebarBahu)
                            .addComponent(tnama))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tPCelana, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tLPinggang, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(tLLeher)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tLPaha)
                                    .addComponent(tSelang)
                                    .addComponent(tLLutut)
                                    .addComponent(tLPinggul, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(tLPergelanganKaki, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLLeher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tpBaju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPCelana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(tLebarBahu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLPinggang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(tLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLPinggul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(tLPerut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLPaha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7)
                    .addComponent(tLPinggulAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSelang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(tPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLLutut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(tLPergelanganKaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLPergelanganTangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(editbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tambahBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        // TODO add your handling code here:
         try{
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/penjahit","root","");
            conn.createStatement().executeUpdate("insert into ukuran values"+"('"+tnama.getText()+"','"+tpBaju.getText()+"','"+tLebarBahu.getText()+"','"+tLD.getText()+"','"+tLPerut.getText()+"','"+tLPinggulAtas.getText()+"','"+tPL.getText()+"','"
                    +tLPergelanganTangan.getText()+"','"+tLLeher.getText()+"','"+tPCelana.getText()+"','"+tLPinggang.getText()+"','"+tLPinggul.getText()+"','"+tLPaha.getText()+"','"+tSelang.getText()+"','"+tLLutut.getText()+
                    "','"+tLPergelanganKaki.getText()+"')");
            tampilkan();
            reset();
            
            JOptionPane.showMessageDialog(null, "Berhasil Menambah");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menambah" + e.getMessage());
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void simpanbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanbtnMouseClicked
        // TODO add your handling code here:
          try{
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/penjahit","root","");
            conn.createStatement().executeUpdate("insert into ukuran values"+"('"+tnama.getText()+"','"+tpBaju.getText()+"','"+tLebarBahu.getText()+"','"+tLD.getText()+"','"+tLPerut.getText()+"','"+tLPinggulAtas.getText()+"','"+tPL.getText()+"','"
                    +tLPergelanganTangan.getText()+"','"+tLLeher.getText()+"','"+tPCelana.getText()+"','"+tLPinggang.getText()+"','"+tLPinggul.getText()+"','"+tLPaha.getText()+"','"+tSelang.getText()+"','"+tLLutut.getText()+
                    "','"+tLPergelanganKaki.getText()+"')");
            tampilkan();
           
            
            JOptionPane.showMessageDialog(null, "Berhasil Menambah");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Menambah" + e.getMessage());
        }
    }//GEN-LAST:event_simpanbtnMouseClicked

    private void tabelukuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelukuranMouseClicked
        // TODO add your handling code here:
        int i = tabelukuran.getSelectedRow();
        if (i>-1){
            tnama.setText(model.getValueAt(i, 0).toString());
            tpBaju.setText(model.getValueAt(i, 1).toString());
            tLebarBahu.setText(model.getValueAt(i, 2).toString());
            tLD.setText(model.getValueAt(i, 3).toString());
            tLPerut.setText(model.getValueAt(i, 4).toString());
            tLPinggulAtas.setText(model.getValueAt(i, 5).toString());
            tPL.setText(model.getValueAt(i, 6).toString());
            tLPergelanganTangan.setText(model.getValueAt(i, 7).toString());
            tLLeher.setText(model.getValueAt(i, 8).toString());
            tPCelana.setText(model.getValueAt(i, 9).toString());
            tLPinggang.setText(model.getValueAt(i, 10).toString());
            tLPinggul.setText(model.getValueAt(i, 11).toString());
            tLPaha.setText(model.getValueAt(i, 12).toString());
            tSelang.setText(model.getValueAt(i, 13).toString());
            tLLutut.setText(model.getValueAt(i, 14).toString());
            tLPergelanganKaki.setText(model.getValueAt(i, 15).toString());
        }
    }//GEN-LAST:event_tabelukuranMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        modelPakaian mp = new modelPakaian();
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/penjahit","root","");
            conn.createStatement().executeUpdate("delete from ukuran where nama_konsumen ='"+ tnama.getText()+ "'");
            
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);

            tampilkan();
           
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data gagal di hapus" + ex.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        try{
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/penjahit","root","");
            conn.createStatement().executeLargeUpdate("update ukuran set panjang_baju ='"+tpBaju.getText()+"',lebar_bahu ='"+tLebarBahu.getText()+"',lingkar_dada ='"+tLD.getText()+"',lingkar_perut ='"+tLPerut.getText()+"',lingkar_pinggulatas ='"+tLPinggulAtas.getText()+"',panjang_lengan ='"+tPL.getText()+
                    "',lingkar_pergelangantangan ='"+tLPergelanganTangan.getText()+"',lingkar_leher ='"+tLLeher.getText()+"',panjang_celana ='"+tPCelana.getText()+"',lingkar_pinggang ='"+tLPinggang.getText()+"',lingkar_pinggul ='"+tLPinggul.getText()+"',lingkar_paha ='"+tLPaha.getText()+"',selangkangan ='"+tSelang.getText()+"',lingkar_lutut ='"+tLLutut.getText()+
                    "',lingkar_pergelangankaki ='"+tLPergelanganKaki.getText()+"' where nama_konsumen ='"+tnama.getText()+"'");
            tampilkan();
           
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(DataKonsumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetbtnActionPerformed
private void reset(){
            tnama.setText("");
            tpBaju.setText("");
            tLebarBahu.setText("");
            tLD.setText("");
            tLPerut.setText("");
            tLPinggulAtas.setText("");
            tPL.setText("");
            tLPergelanganTangan.setText("");
            tLLeher.setText("");
            tPCelana.setText("");
            tLPinggang.setText("");
            tLPinggul.setText("");
            tLPaha.setText("");
            tSelang.setText("");
            tLLutut.setText("");
            tLPergelanganKaki.setText(""); 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ukuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ukuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editbtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JTextField tLD;
    private javax.swing.JTextField tLLeher;
    private javax.swing.JTextField tLLutut;
    private javax.swing.JTextField tLPaha;
    private javax.swing.JTextField tLPergelanganKaki;
    private javax.swing.JTextField tLPergelanganTangan;
    private javax.swing.JTextField tLPerut;
    private javax.swing.JTextField tLPinggang;
    private javax.swing.JTextField tLPinggul;
    private javax.swing.JTextField tLPinggulAtas;
    private javax.swing.JTextField tLebarBahu;
    private javax.swing.JTextField tPCelana;
    private javax.swing.JTextField tPL;
    private javax.swing.JTextField tSelang;
    private javax.swing.JTable tabelukuran;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tpBaju;
    // End of variables declaration//GEN-END:variables
}
